import React, { useState, useMemo } from 'react';
import { useAppStore } from '../../store';
import { useCarbonData } from '../../hooks/useCarbonData';
import { getAllLogsForExport } from '../../services/firestore';
import { exportToGoogleSheets, downloadDataAsJson } from '../../services/sheets';
import { Card, Button, SectionHeader, Badge, MetricCard, Select, FormField, LoadingSpinner } from '../shared';
import { WeeklyBarChart, CategoryDonutChart } from '../charts';
import { formatCO2, kgToTrees, getNationalAverage } from '../../utils/carbonCalc';
import { TARGET_1_5C_KG_YEAR } from '../../constants/emissionFactors';
import { startOfMonth, startOfQuarter, startOfYear, format, subMonths } from 'date-fns';
import jsPDF from 'jspdf';

type PeriodType = 'monthly' | 'quarterly' | 'annual';

export function ReportsPage() {
  const { user, profile, accessToken, addNotification } = useAppStore();
  const [period, setPeriod] = useState<PeriodType>('monthly');
  const [exporting, setExporting] = useState<'sheets' | 'pdf' | 'json' | null>(null);
  const [sheetsUrl, setSheetsUrl] = useState<string | null>(null);

  const days = period === 'monthly' ? 30 : period === 'quarterly' ? 90 : 365;
  const { categoryBreakdown, weeklyData, logs } = useCarbonData(days);

  const totalKg = useMemo(() => logs.reduce((s, l) => s + l.kgCO2e, 0), [logs]);
  const nationalAvg = profile ? getNationalAverage(profile.country) : 7000;
  const annualEquivalent = period === 'monthly' ? totalKg * 12 : period === 'quarterly' ? totalKg * 4 : totalKg;
  const reductionVsAvg = nationalAvg > 0 ? ((nationalAvg - annualEquivalent) / nationalAvg) * 100 : 0;

  const bestCategory = useMemo(() => {
    const filtered = categoryBreakdown.filter((c) => c.kgCO2e > 0);
    if (!filtered.length) return null;
    return filtered.reduce((min, c) => (c.kgCO2e < min.kgCO2e ? c : min), filtered[0]);
  }, [categoryBreakdown]);

  const worstCategory = useMemo(() => {
    const filtered = categoryBreakdown.filter((c) => c.kgCO2e > 0);
    if (!filtered.length) return null;
    return filtered.reduce((max, c) => (c.kgCO2e > max.kgCO2e ? c : max), filtered[0]);
  }, [categoryBreakdown]);

  const periodLabel = useMemo(() => {
    const now = new Date();
    if (period === 'monthly') return format(subMonths(now, 0), 'MMMM yyyy');
    if (period === 'quarterly') return `Q${Math.ceil((now.getMonth() + 1) / 3)} ${now.getFullYear()}`;
    return String(now.getFullYear());
  }, [period]);

  const handleExportSheets = async () => {
    if (!user || !accessToken) {
      addNotification({ type: 'warning', message: 'Connect Google account to export to Sheets.' });
      return;
    }
    setExporting('sheets');
    try {
      const allLogs = await getAllLogsForExport(user.uid);
      const url = await exportToGoogleSheets(allLogs, accessToken, periodLabel);
      setSheetsUrl(url);
      addNotification({ type: 'success', message: '📊 Exported to Google Sheets!' });
    } catch (err: any) {
      addNotification({ type: 'error', message: `Export failed: ${err.message}` });
    } finally {
      setExporting(null);
    }
  };

  const handleExportPDF = async () => {
    setExporting('pdf');
    try {
      const doc = new jsPDF();
      doc.setFontSize(22);
      doc.setTextColor(27, 67, 50);
      doc.text('EcoTrack AI — Carbon Report', 20, 25);
      doc.setFontSize(12);
      doc.setTextColor(108, 117, 125);
      doc.text(`${periodLabel} • ${profile?.displayName ?? ''}`, 20, 35);
      doc.setFontSize(14);
      doc.setTextColor(30, 30, 30);
      doc.text('Summary', 20, 50);
      doc.setFontSize(11);
      const lines = [
        `Total CO₂e: ${formatCO2(totalKg)}`,
        `Annual equivalent: ${formatCO2(annualEquivalent)}`,
        `vs National average: ${reductionVsAvg > 0 ? '-' : '+'}${Math.abs(reductionVsAvg).toFixed(1)}%`,
        `Best category: ${bestCategory?.label ?? '—'}`,
        `Worst category: ${worstCategory?.label ?? '—'}`,
        `Trees equivalent saved: ${kgToTrees(Math.max(0, nationalAvg - annualEquivalent))}`,
      ];
      lines.forEach((line, i) => {
        doc.text(line, 20, 62 + i * 9);
      });
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by EcoTrack AI • ${new Date().toLocaleDateString()}`, 20, 280);
      doc.save(`ecotrack-report-${periodLabel.replace(/\s/g, '-')}.pdf`);
      addNotification({ type: 'success', message: '📄 PDF downloaded!' });
    } catch {
      addNotification({ type: 'error', message: 'PDF export failed.' });
    } finally {
      setExporting(null);
    }
  };

  const handleExportJSON = async () => {
    if (!user) return;
    setExporting('json');
    try {
      const allLogs = await getAllLogsForExport(user.uid);
      downloadDataAsJson({ profile, logs: allLogs, exportDate: new Date().toISOString() }, `ecotrack-data-${Date.now()}.json`);
      addNotification({ type: 'success', message: '💾 Data downloaded as JSON.' });
    } catch {
      addNotification({ type: 'error', message: 'JSON export failed.' });
    } finally {
      setExporting(null);
    }
  };

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="font-display font-bold text-2xl text-eco-ink">Reports 📄</h1>
          <p className="text-eco-slate text-sm mt-1">Your carbon footprint analysis and exports.</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          {(['monthly', 'quarterly', 'annual'] as PeriodType[]).map((p) => (
            <button
              key={p}
              onClick={() => setPeriod(p)}
              aria-pressed={period === p}
              className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${
                period === p ? 'bg-eco-forest text-white' : 'bg-white border border-gray-200 text-eco-slate hover:border-eco-mint'
              }`}
            >
              {p.charAt(0).toUpperCase() + p.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Period label */}
      <div className="flex items-center gap-2">
        <span className="font-display font-bold text-xl text-eco-ink">{periodLabel}</span>
        <Badge variant="green">{days} days</Badge>
      </div>

      {/* Key metrics */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard icon="💨" label="Total CO₂e" value={formatCO2(totalKg)} subvalue="this period" color="#40916C" />
        <MetricCard icon="📉" label="vs National avg" value={`${reductionVsAvg > 0 ? '-' : '+'}${Math.abs(reductionVsAvg).toFixed(0)}%`}
          subvalue={`${formatCO2(nationalAvg)}/yr avg`} color={reductionVsAvg > 0 ? '#40916C' : '#E76F51'} />
        <MetricCard icon="🌱" label="Best category" value={bestCategory?.icon ?? '—'} subvalue={bestCategory?.label ?? 'No data'} color="#74C69D" />
        <MetricCard icon="🌳" label="Trees saved" value={String(kgToTrees(Math.max(0, nationalAvg - annualEquivalent)))} subvalue="vs national avg" color="#1B4332" />
      </div>

      {/* Charts */}
      <div className="grid lg:grid-cols-2 gap-4">
        <Card className="p-5">
          <SectionHeader title="Emissions over time" />
          <WeeklyBarChart data={weeklyData} />
        </Card>
        <Card className="p-5">
          <SectionHeader title="Category breakdown" />
          <CategoryDonutChart categories={categoryBreakdown} />
        </Card>
      </div>

      {/* Category table */}
      <Card className="p-5">
        <SectionHeader title="Category summary" />
        <div className="overflow-x-auto">
          <table className="w-full text-sm" aria-label="Carbon emissions by category">
            <thead>
              <tr className="border-b border-gray-100">
                <th className="text-left py-2 text-eco-slate font-medium">Category</th>
                <th className="text-right py-2 text-eco-slate font-medium">kg CO₂e</th>
                <th className="text-right py-2 text-eco-slate font-medium">% of total</th>
                <th className="text-right py-2 text-eco-slate font-medium">Trend</th>
              </tr>
            </thead>
            <tbody>
              {categoryBreakdown.map((cat) => (
                <tr key={cat.category} className="border-b border-gray-50 hover:bg-eco-mist/30 transition-colors">
                  <td className="py-2.5">
                    <span className="flex items-center gap-2">
                      <span aria-hidden="true">{cat.icon}</span>
                      {cat.label}
                    </span>
                  </td>
                  <td className="text-right py-2.5 font-mono">{cat.kgCO2e.toFixed(2)}</td>
                  <td className="text-right py-2.5">
                    <div className="flex items-center justify-end gap-2">
                      <div className="w-16 h-1.5 bg-eco-mist rounded-full overflow-hidden">
                        <div className="h-full rounded-full" style={{ width: `${cat.percentage}%`, backgroundColor: cat.color }} />
                      </div>
                      <span className="font-medium w-10">{cat.percentage.toFixed(0)}%</span>
                    </div>
                  </td>
                  <td className="text-right py-2.5">
                    <Badge variant={cat.trend === 'down' ? 'green' : cat.trend === 'up' ? 'red' : 'gray'} size="sm">
                      {cat.trend === 'down' ? '↓ Better' : cat.trend === 'up' ? '↑ Higher' : '→ Stable'}
                    </Badge>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Export actions */}
      <Card className="p-5">
        <SectionHeader title="Export data" subtitle="Download or share your carbon report" />
        <div className="grid sm:grid-cols-3 gap-3">
          <button
            onClick={handleExportSheets}
            disabled={!!exporting}
            className="flex items-center gap-3 p-4 rounded-xl border-2 border-gray-100 hover:border-eco-leaf transition-all text-left disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-eco-leaf"
          >
            {exporting === 'sheets' ? <LoadingSpinner size={24} className="text-eco-leaf" /> : <span className="text-3xl" aria-hidden="true">📊</span>}
            <div>
              <p className="font-semibold text-sm text-eco-ink">Google Sheets</p>
              <p className="text-xs text-eco-slate">Full data + chart tab</p>
            </div>
          </button>

          <button
            onClick={handleExportPDF}
            disabled={!!exporting}
            className="flex items-center gap-3 p-4 rounded-xl border-2 border-gray-100 hover:border-eco-leaf transition-all text-left disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-eco-leaf"
          >
            {exporting === 'pdf' ? <LoadingSpinner size={24} className="text-eco-leaf" /> : <span className="text-3xl" aria-hidden="true">📄</span>}
            <div>
              <p className="font-semibold text-sm text-eco-ink">PDF Report</p>
              <p className="text-xs text-eco-slate">Summary document</p>
            </div>
          </button>

          <button
            onClick={handleExportJSON}
            disabled={!!exporting}
            className="flex items-center gap-3 p-4 rounded-xl border-2 border-gray-100 hover:border-eco-leaf transition-all text-left disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-eco-leaf"
          >
            {exporting === 'json' ? <LoadingSpinner size={24} className="text-eco-leaf" /> : <span className="text-3xl" aria-hidden="true">💾</span>}
            <div>
              <p className="font-semibold text-sm text-eco-ink">JSON Export</p>
              <p className="text-xs text-eco-slate">GDPR data download</p>
            </div>
          </button>
        </div>

        {sheetsUrl && (
          <div className="mt-4 p-3 bg-eco-mist rounded-xl flex items-center gap-3">
            <span className="text-eco-leaf">✅</span>
            <a href={sheetsUrl} target="_blank" rel="noopener noreferrer" className="text-sm text-eco-leaf underline hover:text-eco-forest font-medium">
              Open your Google Sheet →
            </a>
          </div>
        )}
      </Card>
    </div>
  );
}
