import type { CarbonLog } from '../types';

// Google Sheets Export Service
// Uses OAuth token from Firebase Google Sign-In

const SHEETS_API = 'https://sheets.googleapis.com/v4/spreadsheets';
const DRIVE_API = 'https://www.googleapis.com/drive/v3/files';

/**
 * Create a new Google Sheet and populate it with carbon log data.
 */
export async function exportToGoogleSheets(
  logs: CarbonLog[],
  accessToken: string,
  period: string
): Promise<string> {
  // 1. Create spreadsheet
  const createRes = await fetch(SHEETS_API, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      properties: { title: `EcoTrack Report — ${period}` },
      sheets: [
        { properties: { sheetId: 0, title: 'Carbon Log', index: 0 } },
        { properties: { sheetId: 1, title: 'Summary', index: 1 } },
      ],
    }),
  });

  if (!createRes.ok) {
    throw new Error(`Failed to create spreadsheet: ${createRes.statusText}`);
  }

  const spreadsheet = await createRes.json();
  const spreadsheetId = spreadsheet.spreadsheetId;
  const spreadsheetUrl = `https://docs.google.com/spreadsheets/d/${spreadsheetId}`;

  // 2. Prepare rows
  const headerRow = [
    'Date',
    'Category',
    'Subcategory',
    'Activity',
    'kg CO₂e',
    'Source',
  ];

  const dataRows = logs.map((log) => {
    const date =
      log.date instanceof Date
        ? log.date.toLocaleDateString()
        : (log.date as any).toDate?.().toLocaleDateString() ?? '';
    return [
      date,
      log.category,
      log.subcategory,
      log.activity,
      log.kgCO2e.toFixed(3),
      log.source,
    ];
  });

  // 3. Write data rows to Carbon Log sheet
  const values = [headerRow, ...dataRows];
  await fetch(
    `${SHEETS_API}/${spreadsheetId}/values/A1?valueInputOption=RAW`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ values }),
    }
  );

  // 4. Format header row (bold, background)
  await fetch(`${SHEETS_API}/${spreadsheetId}:batchUpdate`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      requests: [
        {
          repeatCell: {
            range: { sheetId: 0, startRowIndex: 0, endRowIndex: 1 },
            cell: {
              userEnteredFormat: {
                backgroundColor: { red: 0.106, green: 0.569, blue: 0.424 },
                textFormat: { bold: true, foregroundColor: { red: 1, green: 1, blue: 1 } },
              },
            },
            fields: 'userEnteredFormat(backgroundColor,textFormat)',
          },
        },
        {
          autoResizeDimensions: {
            dimensions: { sheetId: 0, dimension: 'COLUMNS', startIndex: 0, endIndex: 6 },
          },
        },
      ],
    }),
  });

  // 5. Write summary sheet
  const totalKg = logs.reduce((s, l) => s + l.kgCO2e, 0);
  const byCategory = logs.reduce(
    (acc, l) => {
      acc[l.category] = (acc[l.category] ?? 0) + l.kgCO2e;
      return acc;
    },
    {} as Record<string, number>
  );

  const summaryValues = [
    ['EcoTrack AI — Carbon Report'],
    ['Period', period],
    ['Total kg CO₂e', totalKg.toFixed(2)],
    [''],
    ['Category Breakdown'],
    ['Category', 'kg CO₂e', '% of Total'],
    ...Object.entries(byCategory).map(([cat, kg]) => [
      cat,
      kg.toFixed(2),
      `${((kg / totalKg) * 100).toFixed(1)}%`,
    ]),
    [''],
    ['Generated by EcoTrack AI', new Date().toLocaleDateString()],
  ];

  await fetch(
    `${SHEETS_API}/${spreadsheetId}/values/Summary!A1?valueInputOption=RAW`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ values: summaryValues }),
    }
  );

  return spreadsheetUrl;
}

/**
 * Export a JSON blob of all user data for GDPR download.
 */
export function downloadDataAsJson(data: object, filename: string): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
